version: "3.9"

networks:
  default:
    name: kafka
    driver: bridge
    
services:
  zookeeper:
    build: 
      context: kafka
      dockerfile: ../dockerfiles/ZookeeperDockerfile
    volumes:
      - ./data/zookeeper/:/tmp/zookeeper/
      - ./config/zookeeper/zookeeper.properties:/app/config/zookeeper.properties
  
  kafka:
    build: 
      context: kafka
      dockerfile: ../dockerfiles/KafkaDockerfile
    volumes:
      - ./data/kafka/:/tmp/kafka-logs/
      - ./config/kafka-1/server.properties:/app/config/server.properties
    ports:
      - 5000:5000

  ui: 
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    env_file:
      - env/ui.env