version: "3.9"

networks:
  default:
    name: kafka
    driver: bridge

services:
  zookeeper:
    container_name: zookeeper
    build: 
      context: kafka
      dockerfile: ../dockerfiles/ZookeeperDockerfile
    volumes:
      - ./data/zookeeper/:/tmp/zookeeper/
      - ./config/zookeeper/zookeeper.properties:/kafka/config/zookeeper.properties
  
  kafka:
    container_name: kafka
    build: 
      context: kafka
      dockerfile: ../dockerfiles/KafkaDockerfile
    depends_on:
      - zookeeper
    volumes:
      - ./data/kafka/:/tmp/kafka-logs/
      - ./config/kafka-1/server.properties:/kafka/config/server.properties
    ports:
      - 9092:9092

  kafka-ui: 
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:14000
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
      DYNAMIC_CONFIG_ENABLED: true # not necessary for sasl auth, added for tests
  
  kafka-manager:
    container_name: kakfa-manager
    image: hlebalbau/kafka-manager:stable
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:14000
      APPLICATION_SECRET: "random-secret"