FROM openjdk:11.0.10-jre-buster

ENV KAFKA_VERSION 3.4.0
ENV SCALA_VERSION 2.13 
RUN apt-get update && \
    apt-get install -y wget
         
RUN wget "https://downloads.apache.org/kafka/${KAFKA_VERSION}/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz" \
    -O kafka.tgz && \
    tar -xf kafka.tgz

COPY start-zookeeper.sh  /usr/bin
RUN chmod +x  /usr/bin/start-zookeeper.sh

CMD ["start-zookeeper.sh"]